/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:29:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.repository;

import com.ifi.entity.GroupsCatagory;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Jpa repository for GroupsCatagory.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
public interface GroupsCatagoryRepository  extends JpaRepository<GroupsCatagory, Integer> {}