/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:29:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.controller;

import com.ifi.entity.Comment;
import com.ifi.service.CommentServiceImpl;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.MediaType;

@RestController
@CrossOrigin(origins = "*")
@RequestMapping(value = "/comment", produces = "application/hal+json")
public class CommentController {

	private static final Logger LOGGER = LoggerFactory.getLogger(CommentController.class);

	private static final String NOT_FOUND ="Comment not found";

	@Autowired
	private CommentServiceImpl commentService;

	@RequestMapping(value = "/",
			produces = { MediaType.APPLICATION_JSON_VALUE })
	public List<Comment> findAll() {
		List<Comment> list = commentService.findAll();
		return list;
	}


	@GetMapping("{id}")
	public Comment get(@PathVariable("id") Integer id) {
		final Comment comment = commentService.getOne(id);
		LOGGER.info("Comment found : {}", comment);
		return comment;
	}

	@PostMapping(consumes = "application/json")
	public Comment create(@RequestBody Comment comment) {
		LOGGER.info("Comment creation request : {}", comment);
		if (commentService.exist(comment)) {
			LOGGER.info("Comment already exist ! : {}", comment);
			return null;
		} else {
			final Comment created = commentService.create(comment);
			LOGGER.info("Created comment {}", created);
			return created;
		}
	}

	@PutMapping(value = "{id}", consumes = "application/json")
	public Comment update(@PathVariable("id") Integer id, @RequestBody Comment comment) {
		return commentService.update(comment);
	}

	@DeleteMapping("{id}")
	public void delete(@PathVariable("id") Integer id) {
		LOGGER.info("Comment deletion request : {}", resolveIdForLogger(id));
		if (commentService.delete(id)) {
			LOGGER.info("Comment succesfully deleted");
		} else {
			LOGGER.info(NOT_FOUND);
		}
	}

	private String resolveIdForLogger(Integer id) {
		final StringBuilder ids = new StringBuilder();
		ids.append(String.valueOf(id));
		return ids.toString();
	}

}

