/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:29:46 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.controller;

import com.ifi.entity.Role;
import com.ifi.service.RoleServiceImpl;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.MediaType;

@RestController
@CrossOrigin(origins = "*")
@RequestMapping(value = "/role", produces = "application/hal+json")
public class RoleController {

	private static final Logger LOGGER = LoggerFactory.getLogger(RoleController.class);

	private static final String NOT_FOUND ="Role not found";

	@Autowired
	private RoleServiceImpl roleService;

	@RequestMapping(value = "/",
			produces = { MediaType.APPLICATION_JSON_VALUE })
	public List<Role> findAll() {
		List<Role> list = roleService.findAll();
		return list;
	}


	@GetMapping("{id}")
	public Role get(@PathVariable("id") Integer id) {
		final Role role = roleService.getOne(id);
		LOGGER.info("Role found : {}", role);
		return role;
	}

	@PostMapping(consumes = "application/json")
	public Role create(@RequestBody Role role) {
		LOGGER.info("Role creation request : {}", role);
		if (roleService.exist(role)) {
			LOGGER.info("Role already exist ! : {}", role);
			return null;
		} else {
			final Role created = roleService.create(role);
			LOGGER.info("Created role {}", created);
			return created;
		}
	}

	@PutMapping(value = "{id}", consumes = "application/json")
	public Role update(@PathVariable("id") Integer id, @RequestBody Role role) {
		return roleService.update(role);
	}

	@DeleteMapping("{id}")
	public void delete(@PathVariable("id") Integer id) {
		LOGGER.info("Role deletion request : {}", resolveIdForLogger(id));
		if (roleService.delete(id)) {
			LOGGER.info("Role succesfully deleted");
		} else {
			LOGGER.info(NOT_FOUND);
		}
	}

	private String resolveIdForLogger(Integer id) {
		final StringBuilder ids = new StringBuilder();
		ids.append(String.valueOf(id));
		return ids.toString();
	}

}

