/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:29:46 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.controller;

import com.ifi.entity.UserProfile;
import com.ifi.service.UserProfileServiceImpl;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.MediaType;

@RestController
@CrossOrigin(origins = "*")
@RequestMapping(value = "/userProfile", produces = "application/hal+json")
public class UserProfileController {

	private static final Logger LOGGER = LoggerFactory.getLogger(UserProfileController.class);

	private static final String NOT_FOUND ="UserProfile not found";

	@Autowired
	private UserProfileServiceImpl userProfileService;

	@RequestMapping(value = "/",
			produces = { MediaType.APPLICATION_JSON_VALUE })
	public List<UserProfile> findAll() {
		List<UserProfile> list = userProfileService.findAll();
		return list;
	}


	@GetMapping("{id}")
	public UserProfile get(@PathVariable("id") Integer id) {
		final UserProfile userProfile = userProfileService.getOne(id);
		LOGGER.info("UserProfile found : {}", userProfile);
		return userProfile;
	}

	@PostMapping(consumes = "application/json")
	public UserProfile create(@RequestBody UserProfile userProfile) {
		LOGGER.info("UserProfile creation request : {}", userProfile);
		if (userProfileService.exist(userProfile)) {
			LOGGER.info("UserProfile already exist ! : {}", userProfile);
			return null;
		} else {
			final UserProfile created = userProfileService.create(userProfile);
			LOGGER.info("Created userProfile {}", created);
			return created;
		}
	}

	@PutMapping(value = "{id}", consumes = "application/json")
	public UserProfile update(@PathVariable("id") Integer id, @RequestBody UserProfile userProfile) {
		return userProfileService.update(userProfile);
	}

	@DeleteMapping("{id}")
	public void delete(@PathVariable("id") Integer id) {
		LOGGER.info("UserProfile deletion request : {}", resolveIdForLogger(id));
		if (userProfileService.delete(id)) {
			LOGGER.info("UserProfile succesfully deleted");
		} else {
			LOGGER.info(NOT_FOUND);
		}
	}

	private String resolveIdForLogger(Integer id) {
		final StringBuilder ids = new StringBuilder();
		ids.append(String.valueOf(id));
		return ids.toString();
	}

}

