/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:29:46 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.controller;

import com.ifi.entity.User;
import com.ifi.service.UserServiceImpl;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.MediaType;

@RestController
@CrossOrigin(origins = "*")
@RequestMapping(value = "/user", produces = "application/hal+json")
public class UserController {

	private static final Logger LOGGER = LoggerFactory.getLogger(UserController.class);

	private static final String NOT_FOUND ="User not found";

	@Autowired
	private UserServiceImpl userService;

	@RequestMapping(value = "/",
			produces = { MediaType.APPLICATION_JSON_VALUE })
	public List<User> findAll() {
		List<User> list = userService.findAll();
		return list;
	}


	@GetMapping("{userProfileId}")
	public User get(@PathVariable("userProfileId") Integer userProfileId) {
		final User user = userService.getOne(userProfileId);
		LOGGER.info("User found : {}", user);
		return user;
	}

	@PostMapping(consumes = "application/json")
	public User create(@RequestBody User user) {
		LOGGER.info("User creation request : {}", user);
		if (userService.exist(user)) {
			LOGGER.info("User already exist ! : {}", user);
			return null;
		} else {
			final User created = userService.create(user);
			LOGGER.info("Created user {}", created);
			return created;
		}
	}

	@PutMapping(value = "{userProfileId}", consumes = "application/json")
	public User update(@PathVariable("userProfileId") Integer userProfileId, @RequestBody User user) {
		return userService.update(user);
	}

	@DeleteMapping("{userProfileId}")
	public void delete(@PathVariable("userProfileId") Integer userProfileId) {
		LOGGER.info("User deletion request : {}", resolveIdForLogger(userProfileId));
		if (userService.delete(userProfileId)) {
			LOGGER.info("User succesfully deleted");
		} else {
			LOGGER.info(NOT_FOUND);
		}
	}

	private String resolveIdForLogger(Integer userProfileId) {
		final StringBuilder ids = new StringBuilder();
		ids.append(String.valueOf(userProfileId));
		return ids.toString();
	}

}

