package com.ifi.entity;
// Generated Oct 1, 2018 4:26:22 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * GmailUser generated by hbm2java
 */
@Entity
@Table(name = "gmail_user", catalog = "tryhardmore")
public class GmailUser implements java.io.Serializable {

	private int userProfileId;
	private UserProfile userProfile;
	private String facebookId;

	public GmailUser() {
	}

	public GmailUser(UserProfile userProfile, String facebookId) {
		this.userProfile = userProfile;
		this.facebookId = facebookId;
	}

	@GenericGenerator(name = "com.ifi.entity.GmailUserIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "userProfile"))
	@Id
	@GeneratedValue(generator = "com.ifi.entity.GmailUserIdGenerator")

	@Column(name = "user_profile_id", unique = true, nullable = false)
	public int getUserProfileId() {
		return this.userProfileId;
	}

	public void setUserProfileId(int userProfileId) {
		this.userProfileId = userProfileId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "facebook_id", nullable = false, length = 30)
	public String getFacebookId() {
		return this.facebookId;
	}

	public void setFacebookId(String facebookId) {
		this.facebookId = facebookId;
	}

}
