package com.ifi.entity;
// Generated Oct 1, 2018 4:26:22 PM by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GroupsCatagory generated by hbm2java
 */
@Entity
@Table(name = "groups_catagory", catalog = "tryhardmore")
public class GroupsCatagory implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Catagory> catagories = new HashSet<Catagory>(0);

	public GroupsCatagory() {
	}

	public GroupsCatagory(String name) {
		this.name = name;
	}

	public GroupsCatagory(String name, Set<Catagory> catagories) {
		this.name = name;
		this.catagories = catagories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupsCatagory")
	public Set<Catagory> getCatagories() {
		return this.catagories;
	}

	public void setCatagories(Set<Catagory> catagories) {
		this.catagories = catagories;
	}

}
