package com.ifi.entity;
// Generated Oct 1, 2018 4:26:22 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PostTagId generated by hbm2java
 */
@Embeddable
public class PostTagId implements java.io.Serializable {

	private Integer tagId;
	private Integer postId;

	public PostTagId() {
	}

	public PostTagId(Integer tagId, Integer postId) {
		this.tagId = tagId;
		this.postId = postId;
	}

	@Column(name = "tag_id")
	public Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

	@Column(name = "post_id")
	public Integer getPostId() {
		return this.postId;
	}

	public void setPostId(Integer postId) {
		this.postId = postId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PostTagId))
			return false;
		PostTagId castOther = (PostTagId) other;

		return ((this.getTagId() == castOther.getTagId()) || (this.getTagId() != null && castOther.getTagId() != null
				&& this.getTagId().equals(castOther.getTagId())))
				&& ((this.getPostId() == castOther.getPostId()) || (this.getPostId() != null
						&& castOther.getPostId() != null && this.getPostId().equals(castOther.getPostId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTagId() == null ? 0 : this.getTagId().hashCode());
		result = 37 * result + (getPostId() == null ? 0 : this.getPostId().hashCode());
		return result;
	}

}
