/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:29:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.Catagory;
import java.util.List;

public interface CatagoryService {

	public Catagory getOne(Integer id);

	public List<Catagory> findAll();

	public Boolean delete(Integer id);

	public Catagory create(Catagory catagory);

	public Catagory update(Catagory catagory);

	public Boolean exist(Catagory catagory);
}
