/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:29:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;



import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.Comment;
import com.ifi.repository.CommentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class CommentServiceImpl implements CommentService {

	@Autowired
	private CommentRepository commentRepository;

	@Override
	public Comment getOne(Integer id) {
		return commentRepository.findById(id).get();
	}

	@Override
	public Boolean delete(Integer id) {
		if (commentRepository.getOne(id) != null) {
			commentRepository.deleteById(id);
			return true;
		}
		return false;
	}

	@Override
	public Comment create(Comment comment) {
		return commentRepository.save(comment);
	}

	@Override
	public Comment update(Comment commentToUpdate) {
						Comment comment = commentRepository.getOne(commentToUpdate.getId());
																														
				if(commentToUpdate.getPost() !=null) {
			
		}
				if(commentToUpdate.getContent() !=null) {
			
		}
				if(commentToUpdate.getLike() !=null) {
			
		}
				if(commentToUpdate.getUserProfile() !=null) {
			
		}
				if(commentToUpdate.getCreatedTime() !=null) {
			
		}
				if(commentToUpdate.getShowStatus() !=null) {
			
		}
				return commentRepository.save(comment);
	}

	@Override
	public Boolean exist(Comment comment) {
						return commentRepository.existsById(comment.getId());
																													}

	@Override
	public List<Comment> findAll() {
		return commentRepository.findAll();
	}

}


