/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:29:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.Comment;
import java.util.List;

public interface CommentService {

	public Comment getOne(Integer id);

	public List<Comment> findAll();

	public Boolean delete(Integer id);

	public Comment create(Comment comment);

	public Comment update(Comment comment);

	public Boolean exist(Comment comment);
}
