/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:29:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.GroupsCatagory;
import java.util.List;

public interface GroupsCatagoryService {

	public GroupsCatagory getOne(Integer id);

	public List<GroupsCatagory> findAll();

	public Boolean delete(Integer id);

	public GroupsCatagory create(GroupsCatagory groupsCatagory);

	public GroupsCatagory update(GroupsCatagory groupsCatagory);

	public Boolean exist(GroupsCatagory groupsCatagory);
}
