/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:29:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.Post;
import java.util.List;

public interface PostService {

	public Post getOne(Integer id);

	public List<Post> findAll();

	public Boolean delete(Integer id);

	public Post create(Post post);

	public Post update(Post post);

	public Boolean exist(Post post);
}
