/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:29:38 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;



import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.Post;
import com.ifi.repository.PostRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class PostServiceImpl implements PostService {

	@Autowired
	private PostRepository postRepository;

	@Override
	public Post getOne(Integer id) {
		return postRepository.findById(id).get();
	}

	@Override
	public Boolean delete(Integer id) {
		if (postRepository.getOne(id) != null) {
			postRepository.deleteById(id);
			return true;
		}
		return false;
	}

	@Override
	public Post create(Post post) {
		return postRepository.save(post);
	}

	@Override
	public Post update(Post postToUpdate) {
						Post post = postRepository.getOne(postToUpdate.getId());
																																		
				if(postToUpdate.getTitle() !=null) {
			
		}
				if(postToUpdate.getContent() !=null) {
			
		}
				if(postToUpdate.getCatagory() !=null) {
			
		}
				if(postToUpdate.getUserProfile() !=null) {
			
		}
				if(postToUpdate.getCreatedTime() !=null) {
			
		}
				if(postToUpdate.getUpdatedTime() !=null) {
			
		}
				if(postToUpdate.getShowStatus() !=null) {
			
		}
				return postRepository.save(post);
	}

	@Override
	public Boolean exist(Post post) {
						return postRepository.existsById(post.getId());
																																	}

	@Override
	public List<Post> findAll() {
		return postRepository.findAll();
	}

}


