/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:29:46 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.Role;
import java.util.List;

public interface RoleService {

	public Role getOne(Integer id);

	public List<Role> findAll();

	public Boolean delete(Integer id);

	public Role create(Role role);

	public Role update(Role role);

	public Boolean exist(Role role);
}
