/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:29:46 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;



import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.Role;
import com.ifi.repository.RoleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class RoleServiceImpl implements RoleService {

	@Autowired
	private RoleRepository roleRepository;

	@Override
	public Role getOne(Integer id) {
		return roleRepository.findById(id).get();
	}

	@Override
	public Boolean delete(Integer id) {
		if (roleRepository.getOne(id) != null) {
			roleRepository.deleteById(id);
			return true;
		}
		return false;
	}

	@Override
	public Role create(Role role) {
		return roleRepository.save(role);
	}

	@Override
	public Role update(Role roleToUpdate) {
						Role role = roleRepository.getOne(roleToUpdate.getId());
										
				if(roleToUpdate.getRoleName() !=null) {
			
		}
				return roleRepository.save(role);
	}

	@Override
	public Boolean exist(Role role) {
						return roleRepository.existsById(role.getId());
									}

	@Override
	public List<Role> findAll() {
		return roleRepository.findAll();
	}

}


