/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:29:46 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;



import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.Tag;
import com.ifi.repository.TagRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class TagServiceImpl implements TagService {

	@Autowired
	private TagRepository tagRepository;

	@Override
	public Tag getOne(Integer id) {
		return tagRepository.findById(id).get();
	}

	@Override
	public Boolean delete(Integer id) {
		if (tagRepository.getOne(id) != null) {
			tagRepository.deleteById(id);
			return true;
		}
		return false;
	}

	@Override
	public Tag create(Tag tag) {
		return tagRepository.save(tag);
	}

	@Override
	public Tag update(Tag tagToUpdate) {
						Tag tag = tagRepository.getOne(tagToUpdate.getId());
										
				if(tagToUpdate.getName() !=null) {
			
		}
				return tagRepository.save(tag);
	}

	@Override
	public Boolean exist(Tag tag) {
						return tagRepository.existsById(tag.getId());
									}

	@Override
	public List<Tag> findAll() {
		return tagRepository.findAll();
	}

}


