/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:29:46 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.Tag;
import java.util.List;

public interface TagService {

	public Tag getOne(Integer id);

	public List<Tag> findAll();

	public Boolean delete(Integer id);

	public Tag create(Tag tag);

	public Tag update(Tag tag);

	public Boolean exist(Tag tag);
}
