/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:29:46 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;



import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.User;
import com.ifi.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class UserServiceImpl implements UserService {

	@Autowired
	private UserRepository userRepository;

	@Override
	public User getOne(Integer userProfileId) {
		return userRepository.findById(userProfileId).get();
	}

	@Override
	public Boolean delete(Integer userProfileId) {
		if (userRepository.getOne(userProfileId) != null) {
			userRepository.deleteById(userProfileId);
			return true;
		}
		return false;
	}

	@Override
	public User create(User user) {
		return userRepository.save(user);
	}

	@Override
	public User update(User userToUpdate) {
						User user = userRepository.getOne(userToUpdate.getUserProfileId());
																																						
				if(userToUpdate.getEmail() !=null) {
			
		}
				if(userToUpdate.getPassword() !=null) {
			
		}
				if(userToUpdate.getPasswordSalt() !=null) {
			
		}
				if(userToUpdate.getPasswordHashAlgorithm() !=null) {
			
		}
				if(userToUpdate.getPasswordReminderToken() !=null) {
			
		}
				if(userToUpdate.getPasswordReminderExpire() !=null) {
			
		}
				if(userToUpdate.getEmailConfirmToken() !=null) {
			
		}
				if(userToUpdate.getUserStatus() !=null) {
			
		}
				return userRepository.save(user);
	}

	@Override
	public Boolean exist(User user) {
						return userRepository.existsById(user.getUserProfileId());
																																					}

	@Override
	public List<User> findAll() {
		return userRepository.findAll();
	}

}


