/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:29:46 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;



import java.util.List;

import javax.transaction.Transactional;

import com.ifi.entity.UserProfile;
import com.ifi.repository.UserProfileRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class UserProfileServiceImpl implements UserProfileService {

	@Autowired
	private UserProfileRepository userProfileRepository;

	@Override
	public UserProfile getOne(Integer id) {
		return userProfileRepository.findById(id).get();
	}

	@Override
	public Boolean delete(Integer id) {
		if (userProfileRepository.getOne(id) != null) {
			userProfileRepository.deleteById(id);
			return true;
		}
		return false;
	}

	@Override
	public UserProfile create(UserProfile userProfile) {
		return userProfileRepository.save(userProfile);
	}

	@Override
	public UserProfile update(UserProfile userProfileToUpdate) {
						UserProfile userProfile = userProfileRepository.getOne(userProfileToUpdate.getId());
																										
				if(userProfileToUpdate.getFullname() !=null) {
			
		}
				if(userProfileToUpdate.getBirthday() !=null) {
			
		}
				if(userProfileToUpdate.getAvt() !=null) {
			
		}
				if(userProfileToUpdate.getRole() !=null) {
			
		}
				if(userProfileToUpdate.getCreatedTime() !=null) {
			
		}
				return userProfileRepository.save(userProfile);
	}

	@Override
	public Boolean exist(UserProfile userProfile) {
						return userProfileRepository.existsById(userProfile.getId());
																									}

	@Override
	public List<UserProfile> findAll() {
		return userProfileRepository.findAll();
	}

}


