/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:29:46 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.ifi.service;

import com.ifi.entity.UserProfile;
import java.util.List;

public interface UserProfileService {

	public UserProfile getOne(Integer id);

	public List<UserProfile> findAll();

	public Boolean delete(Integer id);

	public UserProfile create(UserProfile userProfile);

	public UserProfile update(UserProfile userProfile);

	public Boolean exist(UserProfile userProfile);
}
